### ISSUE TITLE
Emacs 28 support

### ISSUE THREAD

**Issue by 11xx** [crocket/dired-single#3]
Hello,

Just a quick question: Will this package support Emacs 28 (native comp)? It doesn't seem to work directly, I tried requiring and binding the commands in various ways but it doesn't work yet. Tried via both package.el and straight.el.

TIA

**Comment by crocket** [comment]
I'm not an emacs expert. I just know some emacs lisp.

**Comment by 11xx** [comment]
Got it. Thank you for the package.

**Comment by bobrofon** [comment]
I tried dired-single with Emacs 28.2, and I found only one compatibility problem. `dired-single-up-directory` function doesn't work as intended.
In Emacs 28.1 a new option `dired-kill-when-opening-new-dired-buffer` [was introduced](https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/dired.el?id=5afe27624f7168713611dc9c24043091f8f820b6). And because of that `dired-up-directory` implementation was changed. Like this:
```diff
 	(progn
 	  (if other-window
 	      (dired-other-window up)
-	    (dired up))
+	    (dired--find-possibly-alternative-file up))
 	  (dired-goto-file dir)))))
```
But `dired-single-up-directory` relies on the specific implementation of `dired-up-directory`, and overrides the `dired` function to change `dired-up-directory` behavior.
```elisp
  ;; replace dired with dired-single-buffer
  (cl-letf (((symbol-function 'dired) (symbol-function 'dired-single-buffer)))
    (dired-up-directory other-window)))
```
I made a small fix for this specific problem. And it should be enough to use dired-single with Emacs 28.
